name: myprojectenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scipy
  - matplotlib
  - pytest
  - flake8
  - pip
  - pip:
      - somepippackage==1.0.4
      - anotherpippackage
